import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@sweetalert2/theme-dark/dark.css";
import Wrapper from "./components/Wrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} text-slate-200`}>
        {children}
        <Wrapper />
      </body>
    </html>
  );
}
